version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - echo "Current Dir is " $PWD
      - cd airbnb_stream_data_ingestion
      - pip install -r requirements.txt -t python
      - ls -ltr $PWD/*
  build:
    commands:
      - echo "Zipping deployment package..."
      - echo "Current Dir is " $PWD
      - zip -r9 python.zip python
      - ls -ltr $PWD/*
      - echo "Current Dir is " $PWD
      - cd filterAirbnbBookingRecords
      - zip -r9 filterAirbnbBookingRecords.zip lambda_function.py
      - cd ../ProcessFilteredBookings
      - zip -r9 ProcessFilteredBookings.zip lambda_function.py
      - cd ../ProduceAirbnbBookingData
      - zip -r9 ProduceAirbnbBookingData.zip lambda_function.py
      - cd ..
  post_build:
    commands:
      - echo "Updating Lambda function ..."
      - echo "Current Dir is " $PWD
      - ls -ltr $PWD/*
      - aws lambda publish-layer-version --layer-name ProduceAirbnbBookingDataLayer --description "All Required" --zip-file fileb://python.zip --compatible-runtimes python3.12 python3.11 --compatible-architectures "arm64" "x86_64"
      - layerARN=$(aws lambda list-layer-versions --layer-name ProduceAirbnbBookingDataLayer --query 'LayerVersions[0].LayerVersionArn')
      - echo "Layer Name is ${layerARN}"
      - layerARN=`echo ${layerARN} | sed "s/\"//g"`
      - createFunction=$(echo "aws lambda update-function-code --function-name filterAirbnbBookingRecords --zip-file fileb://filterAirbnbBookingRecords/filterAirbnbBookingRecords.zip")
#     - createFunction=$(echo "aws lambda create-function --function-name filterAirbnbBookingRecords --runtime python3.12 --handler lambda_function.lambda_handler --role arn:aws:iam::120582745863:role/airAnbManagedRole--zip-file fileb://filterAirbnbBookingRecords/filterAirbnbBookingRecords.zip --layers=${layerARN}")
      - echo "Create function is --->" ${createFunction}
      - ${createFunction}

#      - createFunction=$(echo "aws lambda create-function --function-name ProcessFilteredBookings --runtime python3.12 --handler lambda_function.lambda_handler --role arn:aws:iam::120582745863:role/airAnbManagedRole--zip-file fileb://ProcessFilteredBookings/ProcessFilteredBookings.zip --layers=${layerARN}")
      - createFunction=$(echo "aws lambda update-function-code --function-name ProcessFilteredBookings  --zip-file fileb://ProcessFilteredBookings/ProcessFilteredBookings.zip")
      - echo "Create function is --->" ${createFunction}

      - ${createFunction}

      - createFunction=$(echo "aws lambda create-function --function-name ProduceAirbnbBookingData --runtime python3.12 --handler lambda_function.lambda_handler --role arn:aws:iam::120582745863:role/airAnbManagedRole --zip-file fileb://ProduceAirbnbBookingData/ProduceAirbnbBookingData.zip --layers=${layerARN}")
      - echo "Create function is --->" ${createFunction}
      - ${createFunction}

      - echo "Deployment complete!"
